noun = input("Enter a noun ")
verb = input("Enter a verb in the past tense ")
adj = input("Enter an adjective ")
place = input("Enter a body part ")
print("Earlier today, I was at the store when a", adj, noun, verb, "into my", place + ".")
